<?php

/**
 * @file
 * Ring Me main file, hooks implementations.
 */

 /**
  * Implements hook_theme().
  */
function ringme_theme($existing, $type, $theme, $path) {
  return [

    // Button generator.
    'ringme_button_generator' => [
      'variables' => [],
      'template'  => 'ringme-button-generator',
    ],

    // Test page.
    'ringme_generator_preview' => [
      'variables' => [
        'form' => NULL,
      ],
      'template' => 'ringme-generator-preview',
    ],
  ];
}
